#ifndef _STM32F103VE_GPIO_H
#define _STM32F103VE_GPIO_H


#define PIN_PA0  GPIO_Pin_0
#define PIN_PA1  GPIO_Pin_1
#define PIN_PA2  GPIO_Pin_2
#define PIN_PA3  GPIO_Pin_3
#define PIN_PA4  GPIO_Pin_4
#define PIN_PA5  GPIO_Pin_5
#define PIN_PA6  GPIO_Pin_6
#define PIN_PA7  GPIO_Pin_7
#define PIN_PA8  GPIO_Pin_8
#define PIN_PA9  GPIO_Pin_9
#define PIN_PA10 GPIO_Pin_10
#define PIN_PA11 GPIO_Pin_11
#define PIN_PA12 GPIO_Pin_12
#define PIN_PA13 GPIO_Pin_13
#define PIN_PA14 GPIO_Pin_14
#define PIN_PA15 GPIO_Pin_15


#define PIN_PB0  GPIO_Pin_0
#define PIN_PB1  GPIO_Pin_1
#define PIN_PB2  GPIO_Pin_2
#define PIN_PB3  GPIO_Pin_3
#define PIN_PB4  GPIO_Pin_4
#define PIN_PB5  GPIO_Pin_5
#define PIN_PB6  GPIO_Pin_6
#define PIN_PB7  GPIO_Pin_7
#define PIN_PB8  GPIO_Pin_8
#define PIN_PB9  GPIO_Pin_9
#define PIN_PB10 GPIO_Pin_10
#define PIN_PB11 GPIO_Pin_11
#define PIN_PB12 GPIO_Pin_12
#define PIN_PB13 GPIO_Pin_13
#define PIN_PB14 GPIO_Pin_14
#define PIN_PB15 GPIO_Pin_15

#define PIN_PC0  GPIO_Pin_0
#define PIN_PC1  GPIO_Pin_1
#define PIN_PC2  GPIO_Pin_2
#define PIN_PC3  GPIO_Pin_3
#define PIN_PC4  GPIO_Pin_4
#define PIN_PC5  GPIO_Pin_5
#define PIN_PC6  GPIO_Pin_6
#define PIN_PC7  GPIO_Pin_7
#define PIN_PC8  GPIO_Pin_8
#define PIN_PC9  GPIO_Pin_9
#define PIN_PC10 GPIO_Pin_10
#define PIN_PC11 GPIO_Pin_11
#define PIN_PC12 GPIO_Pin_12
#define PIN_PC13 GPIO_Pin_13
#define PIN_PC14 GPIO_Pin_14
#define PIN_PC15 GPIO_Pin_15

#define PIN_PD0  GPIO_Pin_0
#define PIN_PD1  GPIO_Pin_1
#define PIN_PD2  GPIO_Pin_2
#define PIN_PD3  GPIO_Pin_3
#define PIN_PD4  GPIO_Pin_4
#define PIN_PD5  GPIO_Pin_5
#define PIN_PD6  GPIO_Pin_6
#define PIN_PD7  GPIO_Pin_7
#define PIN_PD8  GPIO_Pin_8
#define PIN_PD9  GPIO_Pin_9
#define PIN_PD10 GPIO_Pin_10
#define PIN_PD11 GPIO_Pin_11
#define PIN_PD12 GPIO_Pin_12
#define PIN_PD13 GPIO_Pin_13
#define PIN_PD14 GPIO_Pin_14
#define PIN_PD15 GPIO_Pin_15

#define PIN_PE0  GPIO_Pin_0
#define PIN_PE1  GPIO_Pin_1
#define PIN_PE2  GPIO_Pin_2
#define PIN_PE3  GPIO_Pin_3
#define PIN_PE4  GPIO_Pin_4
#define PIN_PE5  GPIO_Pin_5
#define PIN_PE6  GPIO_Pin_6
#define PIN_PE7  GPIO_Pin_7
#define PIN_PE8  GPIO_Pin_8
#define PIN_PE9  GPIO_Pin_9
#define PIN_PE10 GPIO_Pin_10
#define PIN_PE11 GPIO_Pin_11
#define PIN_PE12 GPIO_Pin_12
#define PIN_PE13 GPIO_Pin_13
#define PIN_PE14 GPIO_Pin_14
#define PIN_PE15 GPIO_Pin_15

  
#endif

